version: '3'
services:

  3boxjs:
    build:
      context: .
      dockerfile: Dockerfile.3boxjs
    volumes:
      - ./3box-js/src:/3box-js/src
      - ./3box-js/webpack.config.js:/3box-js/webpack.config.js
      - ./3box-js/webpack.dev.config.js:/3box-js/webpack.dev.config.js
      - ./3box-js/.babelrc:/3box-js/.babelrc
      - ./3box-js/example:/3box-js/example
    ports:
      - "30000:30000"
    environment:
      - PINNING_NODE=/ip4/127.0.0.1/tcp/4003/ws/ipfs/QmP9WyCh3DkjFJ7Z5okG31D8aAGbJuiNUwsmU3wB7Wu2V9
      - ADDRESS_SERVER_URL=http://127.0.0.1:3001
      - PINNING_ROOM=3box-pinning
      - GRAPHQL_SERVER_URL=http://127.0.0.1:3002
      - PROFILE_SERVER_URL=http://127.0.0.1:8081

  pinning:
    build:
      context: .
      dockerfile: Dockerfile.pinning
    volumes:
      - ./3box-pinning-server/src:/3box-pinning-server/src
    ports:
      - "8081:8081"
      - "4002:4002"
      - "4003:4003"
      - "5002:5002"
      - "9090:9090"
    environment:
      - IPFS_PATH=./ipfs
      - REDIS_PATH=redis
      - ADDRESS_SERVER_URL=http://address:3000
      - ORBITDB_PATH=./orbitdb
    networks:
      - redis-net
      - pinning
      - address-net
    depends_on:
      - redis
      - address

  graphql:
    build:
      context: .
      dockerfile: Dockerfile.graphql
    volumes:
      - ./3box-graphql/src:/3box-graphql/src
    ports:
      - 3002:3000
    environment:
      - PROFILE_SERVER_URL=http://pinning:8081
    depends_on:
      - pinning
    networks:
      - pinning

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  address:
    build:
      context: .
      dockerfile: Dockerfile.address
    volumes:
      - ./3box-address-server/src:/3box-address-server/src
    ports:
      - 3001:3000
    environment:
      - PGHOST=address_db
      - PGDATABASE=mydb
      - PGUSER=threebox
      - PGPASSWORD=myuserpassword
    depends_on:
      - address_db
    networks:
      - address-net
      - pinning

  address_db:
    build:
      context: .
      dockerfile: Dockerfile.address_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=threebox
      - POSTGRES_PASSWORD=myuserpassword
      - POSTGRES_DB=mydb
    networks:
      - address-net

  simulate:
    build:
      context: .
      dockerfile: Dockerfile.simulate
    volumes:
      - ./simulate/src:/simulate/src
      - ./simulate/webpack.config.js:/simulate/webpack.config.js
      - ./simulate/dist:/simulate/dist
    ports:
      - "3033:3033"

networks:
  redis-net:
  pinning:
  address-net:

volumes:
  redis-data:
