FROM node:10

EXPOSE 3000

WORKDIR /3box-address-server

RUN npm install -g serverless

COPY /3box-address-server/package.json /3box-address-server/package-lock.json ./
RUN npm install

COPY /3box-address-server/* ./

ENTRYPOINT ["serverless", "offline", "start"]
