version: '3'
services:

  3boxjs:
    build:
      context: 3box-js
      dockerfile: Dockerfile.example
    volumes:
      - ./3box-js/src:/3box-js/src:ro
      - ./3box-js/example:/3box-js/example
      ## Important: If volume mounting js-ceramic, it needs to be bootstrapped and built locally without hoisting
      # - ./js-ceramic/packages:/3box-js/node_modules/@ceramicnetwork:ro
    ports:
      - "30000:30000"
    environment:
      - PINNING_NODE=/ip4/127.0.0.1/tcp/4003/ws/ipfs/QmP9WyCh3DkjFJ7Z5okG31D8aAGbJuiNUwsmU3wB7Wu2V9
      - CERAMIC_IPFS_NODE=/ip4/127.0.0.1/tcp/4103/ws/ipfs/QmdeRFCwW8wPX3LnmQLZTmR4GPBg9hhRLwndTHyZfWpE1n
      - GRAPHQL_SERVER_URL=http://127.0.0.1:3002
      - PROFILE_SERVER_URL=http://127.0.0.1:8081
      - RENDEZVOUS_ADDRESS=/ip4/127.0.0.1/tcp/9091/ws/p2p-websocket-star/

  ceramic:
    build:
      context: js-ceramic
      dockerfile: Dockerfile.daemon
    ports:
      - 7007:7007
    environment:
      - IPFS_API_URL=http://ipfs:5002
    depends_on:
      - ipfs
    command: >
      bash -c "
        cd packages/ceramic-cli &&
        (sleep 5 && ./bin/ceramic.js watch /ceramic/bafyreidpxlnvr6gqscaeceicsz5tmiyxlzqebsvozjtzue2bky24esqkji &) &&
        (sleep 5 && ./bin/ceramic.js watch /ceramic/bafyreiekd7xj4zungivvamff5pfu7vnf7xroreeaxowntjjilcfwf7d4mq &) &&
        ./bin/ceramic.js daemon --ipfs-api $$IPFS_API_URL
      "

  ipfs:
    build: ipfs
    ports:
      - 4102:4102
      - 4103:4103
      - 5002:5002
      - 9090:9090

  pinning:
    build: 3box-pinning-server
    restart: on-failure
    volumes:
      - ./3box-pinning-server/src:/3box-pinning-server/src:ro
    ports:
      - 4002:4002
      - 4003:4003
    environment:
      - IPFS_PATH=${IPFS_KEY}
      - AWS_BUCKET_NAME=${IPFS_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
      - AWS_S3_ENDPOINT=http://minio:9000
      - AWS_S3_ADDRESSING_STYLE=path
      - AWS_S3_SIGNATURE_VERSION=v4
      - PUBSUB_REDIS_PATH=redis
      - ORBIT_REDIS_PATH=redis_orbit
      - ENTRIES_NUM_REDIS_PATH=redis_entries
      - ORBITDB_PATH=./orbitdb
    depends_on:
      - redis
      - redis_orbit
      - redis_entries
      - minio
    command:
      - npx
      - nodemon
      - ./src/run.js

#  profile_api:
#    build: 3box-api
#    volumes:
#      - ./3box-api/src:/3box-api/src:ro
#    environment:
#      - IPFS_PATH=${IPFS_KEY}
#      - AWS_BUCKET_NAME=${IPFS_BUCKET_NAME}
#      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
#      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
#      - AWS_S3_ENDPOINT=http://minio:9000
#      - AWS_S3_ADDRESSING_STYLE=path
#      - AWS_S3_SIGNATURE_VERSION=v4
#      - ADDRESS_SERVER_URL=http://address:3000
#      - REDIS_PATH=redis
#      - ORBIT_REDIS_PATH=redis_orbit
#    ports:
#      - 8081:8081
#    depends_on:
#      - redis
#      - redis_orbit
#      - address
#      - minio
#    command:
#      - npx
#      - nodemon
#      - ./src/run.js

#   graphql:
#     build:
#       context: 3box-graphql
#       dockerfile: Dockerfile.offline
#     volumes:
#       - ./3box-graphql/src:/3box-graphql/src:ro
#     ports:
#       - 3002:3000
#     environment:
#       - PROFILE_SERVER_URL=http://profile_api:8081
#     depends_on:
#       - profile_api

  redis:
    image: redis:4.0-alpine
    hostname: redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    command:
      - --appendonly yes

  redis_orbit:
    image: redis:4.0-alpine
    hostname: redis_orbit
    volumes:
      - redis-orbit-data:/data
    ports:
      - 6380:6379
    command:
      - --appendonly yes
      - --notify-keyspace-events AKE

  redis_entries:
    image: redis:4.0-alpine
    hostname: redis_entries
    volumes:
      - redis-entries-data:/data
    ports:
      - 6381:6379
    command:
      - --appendonly yes

  minio:
    build:
      context: minio
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    ports:
      - 9000:9000
    command:
      - server
      - /data

  libp2p:
    image: joincolony/star-signal-ws-rendezvous
    environment:
      - DISABLE_METRICS=1
    ports:
      - 9091:9090

volumes:
  redis-data:
  redis-orbit-data:
  redis-entries-data:
