FROM node:10
WORKDIR /3box-pinning-server
COPY /3box-pinning-server/package.json /3box-pinning-server/package.json
COPY /ipfs /3box-pinning-server/ipfs
ADD /3box-pinning-server/package-lock.json /3box-pinning-server/package-lock.json
RUN npm install
EXPOSE  8081 4002 4003 5002 9090 9229
CMD npm run start
