FROM minio/minio:RELEASE.2019-12-30T05-45-39Z

RUN mkdir -p /data/ipfs/data /data/node-1/data

COPY ipfs/blocks /data/ipfs/data/blocks
COPY ipfs/datastore /data/node-1/data/datastore
COPY ipfs/config ipfs/datastore_spec ipfs/version /data/node-1/data/
